(function($){if(document.getElementById('newsletter-popup-form')){$.magnificPopup.open({items:{src:'#newsletter-popup-form'},type:'inline'},0);}
$('.new-products-carousel').owlCarousel({loop:false,responsive:{0:{items:2},360:{items:2},480:{items:2},768:{items:3},992:{items:4},1200:{items:6}},margin:20,nav:true,navText:[],dots:false,autoWidth:false});$('.owl-carousel').owlCarousel({loop:false,responsive:{0:{items:2},360:{items:2},480:{items:2},768:{items:3},992:{items:4},1200:{items:4}},margin:20,nav:true,navText:[],dots:false,autoWidth:false});$('.mobile-side-menu').find('.mmenu-toggle').on('click',function(e){var closestLi=$(this).closest('li');if(closestLi.find('ul').length){closestLi.children('ul').slideToggle(300,function(){closestLi.toggleClass('open');});e.preventDefault();}});$('.mmenu-toggle-btn, #mobile-menu-overlay').on('click',function(e){$('.body').toggleClass('mmenu-open');e.preventDefault();});$('.search-toggle').on('click',function(e){$('.header-search-wrapper').toggleClass('open');e.preventDefault();});if($('#header').data('plugin-options')['stickyEnabled']&&!$('.header-nav').find('.header-logo').length&&!$('.header-nav').find('.cart-dropdown').length){var targetArea=$('.header-nav').find('.container');$('.header-logo, .cart-dropdown').clone(true).prependTo(targetArea);}
if(document.getElementById('newsletter-popup-form')){$.magnificPopup.open({items:{src:'#newsletter-popup-form'},type:'inline'},0);}
$('#change-pass-checkbox').on('change',function(){$('#account-chage-pass').toggleClass('show');});$('.payment-card-check').on('change',function(){var cardArea=$('#payment-credit-card-area');switch($(this).val()){case 'card':cardArea.addClass('show');break;case 'cod':cardArea.removeClass('show');break;case 'bkash':cardArea.removeClass('show');break;}});if($.fn.TouchSpin){$('#product-vqty').TouchSpin({verticalbuttons:true});}
if(typeof noUiSlider==='object'){var priceSlider=document.getElementById('price-slider'),priceLow=document.getElementById('price-range-low'),priceHigh=document.getElementById('price-range-high');noUiSlider.create(priceSlider,{start:[50,250],connect:true,step:1,range:{'min':0,'max':300}});priceSlider.noUiSlider.on('update',function(values,handle){var value=values[handle];if(handle){priceHigh.value=Math.round(value);}else{priceLow.value=Math.round(value);}});priceLow.addEventListener('change',function(){priceSlider.noUiSlider.set([this.value,null]);});priceHigh.addEventListener('change',function(){priceSlider.noUiSlider.set([null,this.value]);});}
if($.fn.elevateZoom){$('#product-zoom').elevateZoom({responsive:true,zoomType:"inner",cursor:"default"});}
$('#productGalleryThumbs').owlCarousel({margin:10,items:4,nav:false,center:false,dots:false,autoplay:false}).on('click','.owl-item',function(e){var ez=$('#product-zoom').data('elevateZoom'),targetLink=$(this).find('a'),smallImg=targetLink.data('image'),bigImg=targetLink.data('zoom-image');$('#product-zoom').attr('data-zoom-image',bigImg);$.magnificPopup.close();ez.swaptheimage(smallImg,bigImg);});var galleryZoom=$('#productGalleryThumbs');galleryZoom.magnificPopup({delegate:'a',type:'image',gallery:{enabled:true},callbacks:{elementParse:function(item){item.src=item.el.attr('data-zoom-image');}}});$('.product-img-zoom').on('click',function(){var current=$('#product-zoom').attr('data-zoom-image');$('#productGalleryThumbs .owl-item').each(function(){if(current==$(this).find('.product-gallery-item').attr('data-zoom-image')){return galleryZoom.magnificPopup('open',$(this).index());}});});$('#productGalleryThumbs').find('a').on('click',function(e){e.preventDefault();});if(getCookie('newsCheck')!=''){$.magnificPopup.close();}
$('.newsletter-subscribe input[type="checkbox"]').on('change',function(){if($(this).prop('checked')){setCookie('newsCheck','true',30);}else{setCookie('newsCheck','true',0);}});function setCookie(cname,cvalue,exdays){var d=new Date();d.setTime(d.getTime()+(exdays*24*60*60*1000));var expires="expires="+d.toUTCString();document.cookie=cname+"="+cvalue+";"+expires+";path=/";}
function getCookie(cname){var name=cname+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' '){c=c.substring(1);}
if(c.indexOf(name)==0){return c.substring(name.length,c.length);}}
return "";}}).apply(this,[jQuery]);